version: '3.9'
services:
  php:
    depends_on:
      - db
    container_name: boda_apache_php
    image: boda:${VERSION_PROYECT}
    build:
      context: ../
      dockerfile: ./docker/apache/build/Dockerfile
      network: host
      args:
        - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}
    environment:
      - ENV_ENVIRONMENT=${ENV_ENVIRONMENT}
      - ENV_SERVER=${ENV_SERVER}
      - ENV_DEBUGER=${ENV_DEBUGER}
    volumes:
      - ../:/var/www/html/proyect
      - ./apache/php.ini:/usr/local/etc/php/php.ini
      - ./apache/vhost:/etc/apache2/sites-enabled
      - ./apache/log:/var/log/apache2
    ports:
      - "80:80"
    profiles: [ "prod","dev" ]
    working_dir: /var/www/html
  db:
    container_name: boda_mysql
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bodaroot
      MYSQL_DATABASE: boda
      MYSQL_USER: userboda
      MYSQL_PASSWORD: Boda22 